### ISSUE TITLE
Simulation Error

### ISSUE THREAD

**Issue by eitanlees** [etonello/crnpy#1]
When I run the `simulation_one-sub_enzyme.py` script from the examples I get the following error. 

> Traceback (most recent call last):
  File "simulation_one-sub_enzyme.py", line 28, in <module>
    data, t = simulate(crn, params, initial, start_t, end_t, incr)
  File "/Users/eitanlees/crnpy/examples/simulation.py", line 51, in simulate
    times)
  File "/Users/eitanlees/anaconda3/lib/python3.6/site-packages/scipy/integrate/odepack.py", line 215, in odeint
    ixpr, mxstep, mxhnil, mxordn, mxords)
RuntimeError: The size of the array returned by func (0) does not match the size of y0 (4).

**Comment by etonello** [comment]
Fixed in 92541ef968f9db21cf01d79c3acb1625b63c771b. Some of the examples did not work with python3. Thank you for reporting!
